# -*- coding: utf-8 -*-
"""Chatbot_with_Meta_Llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u628b9Nws4tWqnV_VP5Q4IFoRIS4TtkT
"""

!pip install transformers torch gradio

!pip install langchain==0.1.16 langchain-community

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from langchain.memory import ConversationBufferMemory

import gradio as gr

import warnings
warnings.filterwarnings("ignore")

from huggingface_hub import login
login("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")

# Load model and tokenizer
model_name = "google/gemma-2-2b-it"
token = "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"

# Check if CUDA is available and move model to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Load model and tokenizer with token
model = AutoModelForCausalLM.from_pretrained(model_name, token=token).to(device)
tokenizer = AutoTokenizer.from_pretrained(model_name, token=token)

# Function to generate chatbot response without chat history
def chatbot_response(user_input):
    # Tokenize input and move to GPU
    inputs = tokenizer(user_input, return_tensors="pt", max_length=512, truncation=True).to(device)

    # Generate response
    outputs = model.generate(**inputs)

    # Decode output
    bot_reply = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Ensure the bot doesn't repeat the user input
    if bot_reply.startswith(user_input):
        bot_reply = bot_reply[len(user_input):].strip()

    return bot_reply

chatbot_response("Hi how are you?")

def chatbot_interface(user_input, history):
    response = chatbot_response(user_input)
    history.append((user_input, response))
    return history, ""

# Creating the Gradio Interface
demo = gr.Blocks()

with demo:
    gr.Markdown("## GenAI Chatbot")
    chatbot = gr.Chatbot()
    with gr.Row():
        user_input = gr.Textbox(placeholder="Type your message here...", lines=1)
        send_button = gr.Button("Send")

    history = gr.State([])

    send_button.click(chatbot_interface, inputs=[user_input, history], outputs=[chatbot, user_input])
    user_input.submit(chatbot_interface, inputs=[user_input, history], outputs=[chatbot, user_input])

# Launch the chatbot
demo.launch(share = True)

